---
- name: Setting Up Node 2
  hosts: node2
  strategy: free
  gather_facts: False
  ignore_errors: true
  tasks:
  - name: Setting Hostname
    hostname: name=node2.example.com
  - name: Creating User Account
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Disabling services
    selinux:
      state: disabled
  - name: Building Host File
    copy:
      dest: /etc/hosts
      content: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4\n:1         localhost localhost.localdomain localhost6 localhost6.localdomain6\n192.168.55.199 repo.example.com repo\n192.168.55.200 control.example.com control\n192.168.55.201 node1.example.com node1\n192.168.55.201 node2.example.com node2\n192.168.55.203 node3.example.com node3\n192.168.55.204 node4.example.com node4"
      force: yes
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/ipa.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    blockinfile:
      dest: /etc/yum.repos.d/ipa.repo
      block: |
       [base]
       name=Base
       baseurl=http://repo/BaseOS
       gpgcheck=0
       enabled=1
       
       [apps]
       name=Apps
       baseurl=http://repo/AppStream
       gpgcheck=0
       enabled=1
    tags: repo
  - name: Configuring network
    command: nmcli con mod "System eth1" ipv4.addresses 192.168.55.202/24 ipv4.gateway 192.168.55.1 ipv4.method manual
  - name: Enabling IPV6
    shell: sysctl net.ipv6.conf.lo.disable_ipv6=0 ; sysctl net.ipv6.conf.all.disable_ipv6=0
  - name: Environment Packages Installed.
    yum: name=man-pages state=present 
    register: yum_sleeper
  - name: Starting services
    service: name=firewalld enabled=true state=started
  - name: Fixing Resolv File
    shell: echo 'nameserver 8.8.8.8' > /etc/resolv.conf
  - name: Creating Welcome Message
    file:
      path: /etc/profile.d/welcome.sh
      state: touch
      mode: 0755
  - name: Erasing Repos
    shell: rm -rf /etc/yum.repos.d/*
  - name: Building Welcome Message
    blockinfile:
      dest: /etc/profile.d/welcome.sh
      block: |
         #!/bin/bash
         #
         echo -e '       
         #           _            _           _           _        _       
         #          /\ \     _   /\ \        /\ \        /\ \    /\ \      
         #         /  \ \   /\_\/  \ \      /  \ \____  /  \ \  /  \ \     
         #        / /\ \ \_/ / / /\ \ \    / /\ \_____\/ /\ \ \/ /\ \ \    
         #       / / /\ \___/ / / /\ \ \  / / /\/___  / / /\ \_\/_/\ \ \   
         #      / / /  \/____/ / /  \ \_\/ / /   / / / /_/_ \/_/   / / /   
         #     / / /    / / / / /   / / / / /   / / / /____/\     / / /    
         #    / / /    / / / / /   / / / / /   / / / /\____\/    / / /  _  
         #   / / /    / / / / /___/ / /\ \ \__/ / / / /______   / / /_/\_\ 
         #  / / /    / / / / /____\/ /  \ \___\/ / / /_______\ / /_____/ / 
         #  \/_/     \/_/\/_________/    \/_____/\/__________/ \________/  
         '"#
         #
         # You are logged into \"`hostname`\" as the \"`whoami`\" account.
         # This system is running `cat /etc/redhat-release`
         #
         "
...